Repository b310-digital/mindwendel, pull requests merged in 2021-03, with the labels that each got.

#84 🔧 added hide button for admin settings
  lib/mindwendel/brainstormings/brainstorming.ex
  lib/mindwendel_web/live/brainstorming_live/show.html.leex
  lib/mindwendel_web/templates/admin/brainstorming/_form.html.leex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/repo/migrations/20210313172908_add_visibility_link_to_settings.exs
Labels: enhancement

#83 🔧 add delete job for old brainstormings
  .env.default
  README.md
  config/runtime.exs
  config/test.exs
  lib/mindwendel/application.ex
  lib/mindwendel/brainstormings.ex
  lib/mindwendel/worker/remove_brainstormings_after_period_worker.ex
  lib/mindwendel_web/templates/admin/brainstorming/edit.html.leex
  lib/mindwendel_web/templates/static_page/home.html.leex
  lib/mindwendel_web/views/admin/brainstorming.ex
  mix.exs
  mix.lock
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/repo/migrations/20210313121036_add_oban_jobs_table.exs
  priv/repo/structure.sql
  test/mindwendel/brainstormings_test.exs
  test/support/factory.ex
Labels: enhancement

#85 Allow customization of label names
  .formatter.exs
  README.md
  assets/css/live/idea_live/_index_component.scss
  assets/package-lock.json
  docs/screenshot.png
  docs/screenshot2.png
  lib/mindwendel/brainstormings.ex
  lib/mindwendel/brainstormings/brainstorming.ex
  lib/mindwendel/brainstormings/idea.ex
  lib/mindwendel/brainstormings/idea_label.ex
  lib/mindwendel_web/controllers/admin/brainstorming_controller.ex
  lib/mindwendel_web/live/brainstorming_live/show.html.leex
  lib/mindwendel_web/live/idea_live/index_component.ex
  lib/mindwendel_web/live/idea_live/index_component.html.leex
  lib/mindwendel_web/templates/admin/brainstorming/_form.html.leex
  lib/mindwendel_web/templates/admin/brainstorming/edit.html.leex
  lib/mindwendel_web/templates/error/error_page.html.eex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/repo/data_migrations/migrate_idea_labels.exs
  priv/repo/migrations/20210306141634_create_brainstorming_labels.exs
  priv/repo/migrations/20210307073759_add_label_id_to_ideas.exs
  priv/repo/migrations/20210314114416_execute_migrate_idea_labels.exs
  test/mindwendel/brainstormings_test.exs
  test/mindwendel_web/live/brainstorming_live/show_sort_by_label_test.exs
  test/mindwendel_web/live/brainstorming_live_test.exs
  test/repo/data_migrations/migrate_idea_labels_test.exs
  test/support/factory.ex
Labels: enhancement

#99 docs: new screenshots with English locale
  docs/screenshot.png
  docs/screenshot2.png
Labels: documentation

#98 fix: path to migration file for release
  priv/repo/migrations/20210314114416_execute_migrate_idea_labels.exs
Labels: bug

#104 build: adjust docker tag version
  .github/workflows/on_release_published__build_publish_release.yml
Labels: enhancement
